id: P3E707F99
initial_creation_type: input
source_metadata:
  Title: '-'
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Svabhāvavādaḥ:
    Text Version: Romanized
    Input Personnel: '-'
    Input Date: '2016'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T17:01:15.875350'
last_modified_at: '2022-03-08T17:01:15.875359'
